net: Use task_struct::__state for napi kthread mode
Since commit 498eaa3 ("sched: Change task_struct::state"), the volatile
of the previously known task_struct::state (now __state) has been removed
in favor of an "unsigned int". Switch to __state for sprd rotation and use
READ_ONCE() since we are only checking the value with the if-clause.

This fixes the following error:

../net/core/dev.c:3947:26: error: no member named 'state' in 'struct task_struct'; did you mean 'stats'?
 3947 |                         if (READ_ONCE(thread->state) != TASK_INTERRUPTIBLE)
      |                                               ^~~~~
      |                                               stats
../include/linux/compiler.h:358:34: note: expanded from macro 'READ_ONCE'
  358 | #define READ_ONCE(x) __READ_ONCE(x, 1)
      |                                  ^
../include/linux/compiler.h:350:17: note: expanded from macro '__READ_ONCE'
  350 |         union { typeof(x) __val; char __c[1]; } __u;                    \
      |                        ^
../include/linux/sched.h:739:34: note: 'stats' declared here
  739 |         struct sched_statistics         stats;
      |                                         ^

Fixes: 611718dfdde66 ("net: fix race between napi kthread mode and busy poll")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>