xiaomi_stock_defconfig: Enable all configs required by kernel FCM 7
This is to fix the following compilation error with FCM 7:

2026-08-28 21:37:45 - check_target_files_vintf.py - INFO    : stderr: ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 7).
For kernel requirements at matrix level 7, Kernel config errors:
    Missing config CONFIG_AS_IS_LLVM
    Missing config CONFIG_NET_SCH_TBF
    Missing config CONFIG_KFENCE
: Success

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>