binder: Compile out binder_[return|command]_strings on !FTRACE
Promote binder_return_strings and binder_command_strings arrays out
of CONFIG_ANDROID_BINDER_LOGS so that compilation doesn't error out
when CONFIG_FTRACE is enabled. Furthermore, guard the arrays with
CONFIG_FTRACE since they are only ever needed by trace events.

Otherwise with CONFIG_FTRACE=y, the following compilation errors can
be seen:

In file included from ../drivers/android/binder.c:6524:
In file included from ../drivers/android/./binder_trace.h:414:
In file included from ../include/trace/define_trace.h:96:
In file included from ../include/trace/trace_events.h:394:
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
                  _IOC_NR(__entry->cmd) < ARRAY_SIZE(binder_command_strings) ?
                                                     ^
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
../drivers/android/./binder_trace.h:388:6: error: use of undeclared identifier 'binder_command_strings'
                          binder_command_strings[_IOC_NR(__entry->cmd)] :
                          ^
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
                  _IOC_NR(__entry->cmd) < ARRAY_SIZE(binder_return_strings) ?
                                                     ^
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
../drivers/android/./binder_trace.h:404:6: error: use of undeclared identifier 'binder_return_strings'
                          binder_return_strings[_IOC_NR(__entry->cmd)] :
                          ^

Fixes: 22bc69c4e9686 ("binder: Conditionally compile logging")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>